### ISSUE TITLE
Task smart button does not display BR related task (displays all tasks now)

### ISSUE THREAD

**Issue by fausthuang** [OCA/business-requirement#141] opened 2017-05-17 10:22 UTC
Currently, in BR screen, if we click the task smart button, it will not list the tasks related with this BR, but all tasks will be list.  
actually, should just show this BR's tasks.

**Comment by elicoidal** [comment] 2017-05-17 11:41
Actually not sure: we cannot reproduce in Runbot so maybe this is a local issue.

**Comment by rubencabrera** [comment] 2017-05-25 08:17
Happened to me too, but seems to be fixed on 8.0

**Comment by rubencabrera** [comment] 2017-06-08 09:27
I cannot reproduce this anymore, can you confirm the problem persists and give a bit more insight on which modules you have installed?

**Comment by elicoidal** [comment] 2017-06-08 10:07
We have the issue in our ERP but cannot reproduce it here. 
I think this is linked to another module so I will close this issue here and open it privately

**Closed as completed by elicoidal** 2017-06-08 10:07 UTC
Labels: bug
